/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package edu.duke.yz723.battleship;

import java.io.*;

public class App {
    final TextPlayerV2 player1;
    final TextPlayerV2 player2;

    /**
     * App's constructor initialize TextPlayer1 and TextPlayer2
     * @param p1
     * @param p2
     */
    public App(TextPlayerV2 p1, TextPlayerV2 p2) {
        player1 = p1;
        player2 = p2;
    }

    /**
     * For now only has player1 doOnePlacement
     * @throws IOException IO exception
     */
    public void doPlacementPhase() throws IOException{
        player1.doPlacementPhase();
        player2.doPlacementPhase();
    }
    //this is the Version 2 "doAttackPhase"
    public void doAttackPhase_v2() throws IOException{
        boolean flag = true;
        while(flag){
            //in version 2, this is playOneRound. State is true, game not end. state is false, game end
            boolean player1_state = player1.playOneRound(player2.name, player2.theBoard, player2.view);
            if (!player1_state){
                flag = false;
                continue;
            }
            if (!player2.playOneRound(player1.name, player1.theBoard, player1.view)){ flag = false;}
        }
    }
    public void doComputerChosePhase() throws IOException{
        player1.doRobotChosePhase();
        player2.doRobotChosePhase();
    }

    public static void main(String[] args) throws IOException {
        Board<Character> b1 = new BattleShipBoard<Character>(10, 20, 'X');
        Board<Character> b2 = new BattleShipBoard<Character>(10, 20,'X');
        BufferedReader input = new BufferedReader(new InputStreamReader(System.in));
        V2ShipFactory factory = new V2ShipFactory();
        TextPlayerV2 p1 = new TextPlayerV2("A", b1, input, System.out, factory);
        TextPlayerV2 p2 = new TextPlayerV2("B", b2, input, System.out, factory);
        App app = new App(p1, p2);
        app.doComputerChosePhase();
        app.doPlacementPhase();
        app.doAttackPhase_v2();
    }
}
